In [8]:
import pandas as pd

# If refering to Excel, use: pd.read_excel('[name].xlsx', sheet_name='XXX')
df_fossil_inflows = pd.read_csv('/Users/charlottewestenberg/Thesis/00data/Fossil inflows.csv')

df_fossil_inflows.head()

,Flow,Added info,Amount in dataset,Unit in dataset,Amount_tonnes,Carrier,Type,Source
0,"Crude oil, NGL, refinery feedstocks, additives...",Indigenous production,"19,057.031",thousand_tonnes,"19,057,031.",Crude oil,Inflow,https://ec.europa.eu/eurostat/databrowser/view...
1,"Crude oil, NGL, refinery feedstocks, additives...",Imports,"497,079.537",thousand_tonnes,"497,079,537.",Crude oil,Inflow,https://ec.europa.eu/eurostat/databrowser/view...
2,"Crude oil, NGL, refinery feedstocks, additives...",Exports,"14,406.378",thousand_tonnes,"14,406,378.",Crude oil,Outflow,https://ec.europa.eu/eurostat/databrowser/view...
3,"Crude oil, NGL, refinery feedstocks, additives...",Change in stock,"4,042.544",thousand_tonnes,"4,042,544.",Crude oil,Stock,https://ec.europa.eu/eurostat/databrowser/view...
4,Oil products,Imports,"288,398.077",thousand_tonnes,"288,398,077.",Refined oil,Inflow,https://ec.europa.eu/eurostat/databrowser/view...

In [10]:
df_fossil_inflows_clean = df_fossil_inflows.drop(columns=['Amount in dataset', 'Unit in dataset', 'Source'])

df_fossil_inflows_clean.head()

,Flow,Added info,Amount_tonnes,Carrier,Type
0,"Crude oil, NGL, refinery feedstocks, additives...",Indigenous production,"19,057,031.",Crude oil,Inflow
1,"Crude oil, NGL, refinery feedstocks, additives...",Imports,"497,079,537.",Crude oil,Inflow
2,"Crude oil, NGL, refinery feedstocks, additives...",Exports,"14,406,378.",Crude oil,Outflow
3,"Crude oil, NGL, refinery feedstocks, additives...",Change in stock,"4,042,544.",Crude oil,Stock
4,Oil products,Imports,"288,398,077.",Refined oil,Inflow

In [ ]:
merged = df1.merge(df2, left_on="Flow", right_on="Fuel")